### ISSUE TITLE
Unable to compile ffmpeg in new l4t 34.1 ubuntu 20.04

### ISSUE THREAD

**Issue by aimaicai** [jocover/jetson-ffmpeg#115]
Hi, I've recently upgrade my jetson agx to the latest version (ubuntu 20.04 with l4t 34.1). I follow the guide to enable the nvmpi codec for ffmpeg (4.2.2), but it fail on configure:
ERROR: nvmpi not found using pkg-config
The package is present, so i check the configure.log in the ffbuild folder and I get this:
/usr/bin/ld: /usr/local/lib/libnvmpi.so: undefined reference to `NvBufSurfaceMap'
/usr/bin/ld: /usr/local/lib/libnvmpi.so: undefined reference to `NvBufSurfaceFromFd'
/usr/bin/ld: /usr/local/lib/libnvmpi.so: undefined reference to `NvBufSurfaceUnMap'
Have anyone been able to compile ffmpeg with the nvmpi codecs enabled?
Thanks

**Comment by russ-go** [comment]
From the 34.1 Developer Preview Release Notes:

> Buffer management and buffer transform related API based on nvbuf_utils, defined in
> nvbuf_utils.h, are deprecated in this release. From Jetson Linux release 34.0.1 EA
> forward, NVIDIA recommends using the new API based on nvutils, defined in
> nvbufsurface.h and nvbufsurftransform.h.
> See the nvbuf_utils to NvUtils Migration Guide for information to facilitate your migration to
> the new API.

Likely the case.  I'm checking out the migration guide now....  
[migration guide](https://developer.nvidia.com/sites/default/files/akamai/embedded/nvbuf_utils_to_nvutils_migration_guide.pdf)

I'm not a programmer, but the migration seems pretty straight forward.

**Comment by eusoubrasileiro** [comment]
@russ-go I am looking forward for your progress, on the same page as you.

**Comment by vladirai** [comment]
Same issue on jetson xavier nx with the latest version (Jetpack 5.0.1, ubuntu 20.04 with l4t 34.1.1). Attaching config.log
[config.log](https://github.com/jocover/jetson-ffmpeg/files/9127211/config.log)
.

**Comment by xsacha** [comment]
Has anyone done this conversion yet? So I don't redo all their work.

**Comment by 21ramil** [comment]
@aimaicai  I'm wondering how you solved this problem

**Comment by xsacha** [comment]
Apparently nvidia has added hardware jetson decoder support to ffmpeg, 2 years ago, already.
https://forums.developer.nvidia.com/t/hardware-accelerated-video-playback-with-l4t-ffmpeg/154019/7

There's also this fork, which has nvidia's method and this method (for encoding support mainly) + ported to ffmpeg 4.4:
https://github.com/LinusCDE/mad-jetson-ffmpeg

**Comment by HTani** [comment]
You can build it by adding "-L/usr/lib/aarch 64 -linux-gnu/tegra-lnvbufsurface" to Libs in jetson-ffmeg/nvmpi.pc.in.

> --- nvmpi.pc.in.org	2023-01-13 10:40:43.210327891 +0900
> +++ nvmpi.pc.in	2023-01-16 13:16:17.057770034 +0900
> @@ -8,5 +8,5 @@
>  Version: @PROJECT_VERSION@
>  
>  Requires:
> -Libs: -L${libdir} -lnvmpi
> +Libs: -L${libdir} -lnvmpi -L/usr/lib/aarch64-linux-gnu/tegra -lnvbufsurface
>  Cflags: -I${includedir} 

It works on ffmpeg-4.2.7, Ubuntu 20.04.04 LTS/Orin (JetPack 5.0.2).

**Comment by shunguang** [comment]
os: ubuntu 20.04 LTS, 
jetpack: 5.0.2-b231
ffmpeg git info:
remote.origin.url=git://source.ffmpeg.org/ffmpeg.git
remote.origin.fetch=+refs/heads/release/4.2:refs/remotes/origin/release/4.2
branch.release/4.2.remote=origin
branch.release/4.2.merge=refs/heads/release/4.2

I follow @HTani 's suggestion, but has new errors

----- from ./ffbuild/config.log -----------
BEGIN /tmp/ffconf.lUMlGBb1/test.c
    1   #include <nvmpi.h>
    2   #include <stdint.h>
    3   long check_nvmpi_create_decoder(void) { return (long) nvmpi_create_decoder; }
    4   int main(void) { int ret = 0;
    5    ret |= ((intptr_t)check_nvmpi_create_decoder) & 0xFFFF;
    6   return ret; }
END /tmp/ffconf.lUMlGBb1/test.c
gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -I/usr/local/cuda-11.4/include -I/usr/local/include -std=c11 -fomit-frame-pointer -fPIC -pthread -I/usr/local/include -c -o /tmp/ffconf.lUMlGBb1/test.o /tmp/ffconf.lUMlGBb1/test.c
gcc -L/usr/local/cuda-11.4/lib64 -L/usr/local/lib -L/usr/lib/aarch64-linux-gnu -Wl,--as-needed -Wl,-z,noexecstack -I/usr/local/include -o /tmp/ffconf.lUMlGBb1/test /tmp/ffconf.lUMlGBb1/test.o
/usr/bin/ld: /tmp/ffconf.lUMlGBb1/test.o: in function `check_nvmpi_create_decoder':
test.c:(.text+0x0): **undefined reference to `nvmpi_create_decoder'**
/usr/bin/ld: test.c:(.text+0x4): **undefined reference to `nvmpi_create_decoder'**
collect2: error: ld returned 1 exit status
ERROR: **nvmpi not found using pkg-config**
``
Any suggestions @HTani ? Thanks

**Comment by shunguang** [comment]
P.S.:
(1) By the following check, nvmpi_create_decoder is in the lib. 
nvidia@ubuntu:/usr/local/lib$ nm /usr/local/lib/libnvmpi.a | grep -w T | grep -E 'nvmpi_create_decoder'
0000000000000d3c T nvmpi_create_decoder
nvidia@ubuntu:/usr/local/lib$ nm /usr/local/lib/libnvmpi.so | grep -w T | grep -E 'nvmpi_create_decoder'
00000000000118e0 T nvmpi_create_decoder

(2) here is my config cmd:
/media/nvidia/pkg/ffmpeg$ ./configure --disable-static --enable-shared --enable-nonfree --enable-libnpp --enable-nvmpi --enable-gpl --disable-opencl --extra-cflags="-I/usr/local/cuda-11.4/include -I/usr/local/include" --extra-ldflags="-L/usr/local/cuda-11.4/lib64 -L/usr/local/lib -L/usr/lib/aarch64-linux-gnu"

**Comment by minghaohsu410168** [comment]
> You can build it by adding "-L/usr/lib/aarch 64 -linux-gnu/tegra-lnvbufsurface" to Libs in jetson-ffmeg/nvmpi.pc.in.
> 
> > --- nvmpi.pc.in.org	2023-01-13 10:40:43.210327891 +0900
> > +++ nvmpi.pc.in	2023-01-16 13:16:17.057770034 +0900
> > @@ -8,5 +8,5 @@
> > Version: @PROJECT_VERSION@
> > Requires:
> > -Libs: -L${libdir} -lnvmpi
> > +Libs: -L${libdir} -lnvmpi -L/usr/lib/aarch64-linux-gnu/tegra -lnvbufsurface
> > Cflags: -I${includedir}
> 
> It works on ffmpeg-4.2.7, Ubuntu 20.04.04 LTS/Orin (JetPack 5.0.2).

@HTani  It works after I modified nvmpi.pc file. You save my life!! Thank you.

**Comment by HTani** [comment]
@shunguang 
Have you added the path of the nvmpi.pc file to the environment variable PKG_CONFIG_PATH?

**Comment by shunguang** [comment]
@HTani and @minghaohsu410168  Thanks for your kindly reply. it was a silly  mistake when  interpreted your following   message.
```
-Libs: -L${libdir} -lnvmpi
+Libs: -L${libdir} -lnvmpi -L/usr/lib/aarch64-linux-gnu/tegra -lnvbufsurface

```
at here  "-Libs" and "+Libs" came from your git diff,  notthe contents in  your nvmpi.pc.in file. When i changed them as
```
# Libs: -L${libdir} -lnvmpi
Libs: -L${libdir} -lnvmpi -L/usr/lib/aarch64-linux-gnu/tegra -lnvbufsurface

```
in my nvmpi.pc.in, it passed. but still have some minor issues. Anyway, here is my build note
https://github.com/shunguang/HowTo/blob/master/how-to-build-ffmpeg-4-jetson.txt

**Comment by gjrtimmer** [comment]
This is fixed in the [gjrtimmer/jetson-ffmpeg](https://github.com/gjrtimmer/jetson-ffmpeg) fork. Starting with JetPack 5, NVIDIA replaced `nvbuf_utils` with `NvBufSurface`/NvUtils, which breaks the original CMakeLists.txt that looks for the old library. The fork's CMake build auto-detects which buffer API is available — if `nvbufsurface.h` is present it links against the NvBufSurface libraries and defines `WITH_NVUTILS`, otherwise it falls back to the legacy `nvbuf_utils`. Works on both JetPack 4.x and 5.x/6.x without manual changes. FFmpeg versions 6.0 through 8.1 are supported and tested on Orin hardware.
